### ISSUE TITLE
Create Functional Specifications for CRM

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/lib-crm#1]
Michael and I will be working on creating the spec.

**Comment by mstuart-ucsd** [comment]
Link for the functional spec: https://docs.google.com/document/d/1AnPkKXF9FKHY15gt_ql8I1pt557YmMqLUdsJgITj79s/edit?usp=sharing

**Comment by VivianChu** [comment]
Thanks @mstuart-ucsd
